# Load all necessary packages
library(dplyr)
library(stringr)
library(shiny)
library(bs4Dash)
library(shinyjs)
library(highcharter)
library(ggplot2)
library(shinybrowser)
library(fontawesome)
library(bslib)
library(memoise)
library(shinythemes)
library(tgAPI)
library(BFS)
library(readxl)
library(openxlsx)
library(TGexcel)

